name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Nightly build at 7:15 AM (UDT)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux_amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check linux version
        run: uname -a
      - name: linux all
        run: |
          make clean test CC=gcc MEMSAN=1
          make clean test CC=clang MEMSAN=1
          make clean all CC=gcc
          make clean all CC=clang
          ldd lib/libfam.so  | grep "statically linked" || { echo "not statically linked!"; exit 1; }
          UNDEFINED_COUNT=$(nm lib/libfam.so | grep " U " | grep -v "U environ" | wc -l)
          if [ "$UNDEFINED_COUNT" -ne 0 ]; then
            echo "Error: Found $UNDEFINED_COUNT undefined symbols other than environ"
            exit 1
          fi
  linux_aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to latest version for better compatibility

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Update to latest version
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Add Buildx for multi-arch support

      - name: Verify QEMU setup
        run: docker run --rm --platform linux/arm64 arm64v8/ubuntu:latest uname -m

      - name: Run in ARM64 environment
        run: |
          docker run --rm --platform linux/arm64 -v $(pwd):/work -w /work arm64v8/ubuntu:latest bash -c "
            uname -a &&
            apt-get update &&
            apt-get install -y make gcc clang &&
            make clean test CC=gcc MEMSAN=1 &&
             make clean test CC=clang MEMSAN=1 &&
            make clean all CC=gcc &&
            make clean all CC=clang"
